In [ ]:
import numpy as np
from sklearn.model_selection import GridSearchCV
from numpy import genfromtxt
import pandas as pd

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

from sklearn.decomposition import PCA

In [ ]:
DataFrame_Train=pd.read_csv('train.csv', header=None)
DataFrame_Tt=pd.read_csv('train-target.csv', header=None)
DataFrame_Sample=genfromtxt('sample-submission.csv')
DataFrame_Test=pd.read_csv('test.csv', header=None)
DataFrame_Train

              0           1           2   ...          27          28          29
0    -220.530530  -70.197440  119.035181  ...   40.680890  -37.942655   33.838225
1      -8.536541   -8.305435 -117.828269  ...  -32.101939  -52.255449   -4.826111
2     126.229973  133.463504 -105.511797  ... -117.205053 -107.835928  -93.990332
3     369.571563   11.850181 -299.969407  ...  -25.218215  121.674228  -16.877368
4     -99.563708  -85.166292  -73.363391  ... -132.875142    3.492953  -15.799596
...          ...         ...         ...  ...         ...         ...         ...
9995  -91.804097   96.380816  -93.520627  ...  100.397658  -83.305311 -132.648400
9996 -232.083597  -60.861115   45.472736  ...   35.417264  -66.463502    5.783203
9997 -182.455289  -73.963540 -221.763797  ...  -55.564211 -207.574071   86.333468
9998 -268.344148   53.342079 -176.197832  ...   -7.932393    2.626694   78.433097
9999 -766.308667 -136.240073   26.516587  ...  152.856744  -68.890937   56.441209

[10000 rows x 30 columns]

In [ ]:
inputs = keras.Input(shape=(30,))

layer_1 = layers.Dense(30,kernel_initializer='random_normal',activation="relu")(inputs)
drop_1 = layers.Dropout(0.25)(layer_1)

layer_2 = layers.Dense(30,kernel_initializer='random_normal',activation="relu")(drop_1)
drop_2 = layers.Dropout(0.25)(layer_2)

layer_3 = layers.Dense(30,kernel_initializer='random_normal',activation="relu")(drop_2)
drop_3 = layers.Dropout(0.25)(layer_3)

softmax_1 = layers.Softmax()(drop_3)
outputs = layers.Dense(1)(softmax_1)
model = keras.Model(inputs=inputs, outputs=outputs, name="Neural_2")

model.compile(loss='mse',optimizer='adam')

model.fit(DataFrame_Train,DataFrame_Tt, batch_size=200, epochs=15, validation_split=0.2)

y_predict=model.predict(DataFrame_Test)

MyData = pd.DataFrame(y_predict)
MyData.to_csv("Machine_Learning_Neural.csv",header=None, index=None)

Epoch 1/15
40/40 [==============================] - 0s 5ms/step - loss: 0.3204 - val_loss: 0.2615
Epoch 2/15
40/40 [==============================] - 0s 3ms/step - loss: 0.2552 - val_loss: 0.2504
Epoch 3/15
40/40 [==============================] - 0s 2ms/step - loss: 0.2481 - val_loss: 0.2431
Epoch 4/15
40/40 [==============================] - 0s 2ms/step - loss: 0.2415 - val_loss: 0.2308
Epoch 5/15
40/40 [==============================] - 0s 2ms/step - loss: 0.2311 - val_loss: 0.2188
Epoch 6/15
40/40 [==============================] - 0s 2ms/step - loss: 0.2194 - val_loss: 0.2044
Epoch 7/15
40/40 [==============================] - 0s 2ms/step - loss: 0.2068 - val_loss: 0.1943
Epoch 8/15
40/40 [==============================] - 0s 2ms/step - loss: 0.1949 - val_loss: 0.1788
Epoch 9/15
40/40 [==============================] - 0s 2ms/step - loss: 0.1867 - val_loss: 0.1732
Epoch 10/15
40/40 [==============================] - 0s 2ms/step - loss: 0.1787 - val_loss: 0.1655
Epoch 11/15
40/40 [==============================] - 0s 2ms/step - loss: 0.1692 - val_loss: 0.1559
Epoch 12/15
40/40 [==============================] - 0s 2ms/step - loss: 0.1653 - val_loss: 0.1486
Epoch 13/15
40/40 [==============================] - 0s 2ms/step - loss: 0.1618 - val_loss: 0.1443
Epoch 14/15
40/40 [==============================] - 0s 2ms/step - loss: 0.1520 - val_loss: 0.1439
Epoch 15/15
40/40 [==============================] - 0s 2ms/step - loss: 0.1456 - val_loss: 0.1319

In [ ]:
MyData.min()

0    0.11057
dtype: float32